<html>
<head>
        <title>Заголовок</title>

        <!-- Stylecss -->
        <link rel="stylesheet" href="css/style.css">

        <!-- Favicons -->
        <link rel="shortcut icon" type="image/png" href="img/fav-icon.png"/>  

</head>
    
<body>